description = "Software Engineer based in Germany"
homepage.layout = "page"

colorScheme = "avocado"
dateFormat = "2006-02-01"

[author]
  name = "Tobi"
  bio = "Software Engineer based in Germany"
  image = "img/avatar.jpg"
  links = [
    { github = "https://github.com/twobiers" }
  ]

[article]
    showComments = true

[entry]
    meta = ["date", "categories", "tags"]

enableCodeCopy = true